{
  "version": 1,
  "account": {
    "displayName": "adekiirfan",
    "address": "adekiirfan@gmail.com"
  },
  "services": [
    { "id": "youtube",   "name": "YouTube",               "slug": "youtube",            "bg": "#980520", "iconColor": "ffffff", "totalCount": 23 },
    { "id": "google",    "name": "Google",                "slug": "google",             "bg": "#950366", "iconColor": "ffffff", "totalCount": 48 },
    { "id": "facebook",  "name": "Facebook",              "slug": "facebook",           "bg": "#187792", "iconColor": "ffffff", "totalCount": 36 },
    { "id": "instagram", "name": "Instagram",             "slug": "instagram",          "bg": "#944056", "iconColor": "ffffff", "totalCount": 18 },
    { "id": "whatsapp",  "name": "WhatsApp",              "slug": "whatsapp",           "bg": "#258366", "iconColor": "ffffff", "totalCount": 27 },
    { "id": "github",    "name": "GitHub",                "slug": "github",             "bg": "#650808", "iconColor": "ffffff", "totalCount": 15 },
    { "id": "cloud",     "name": "Cloud (AWS/Azure/GCP)", "slug": "amazonwebservices",  "bg": "#154465", "iconColor": "ff9900", "totalCount": 12 },
    { "id": "microsoft", "name": "Microsoft",             "slug": "microsoft",          "bg": "#870488", "iconColor": "ffffff", "totalCount": 20 },
    { "id": "telegram",  "name": "Telegram",              "slug": "telegram",           "bg": "#96743",  "iconColor": "ffffff", "totalCount": 8  },
    { "id": "twitter",   "name": "Twitter / X",           "slug": "x",                  "bg": "#704570", "iconColor": "ffffff", "totalCount": 9  },
    { "id": "linkedin",  "name": "LinkedIn",              "slug": "linkedin",           "bg": "#458933", "iconColor": "ffffff", "totalCount": 7  },
    { "id": "amazon",    "name": "Amazon",                "slug": "amazon",             "bg": "#349540", "iconColor": "ffffff", "totalCount": 14 },
    { "id": "tiktok",    "name": "TikTok",                "slug": "tiktok",             "bg": "#830543", "iconColor": "ffffff", "totalCount": 6  },
    { "id": "shopee",    "name": "Shopee",                "slug": "shopee",             "bg": "#784709", "iconColor": "ffffff", "totalCount": 9  },
    { "id": "tokopedia", "name": "Tokopedia",             "slug": "tokopedia",          "bg": "#245038", "iconColor": "ffffff", "totalCount": 7  },
    { "id": "medium",    "name": "Medium",                "slug": "M",                  "bg": "#497632", "iconColor": "ffffff", "totalCount": 2  },
    { "id": "snackvideo","name": "SnackVideo",            "slug": "SnackVideo",         "bg": "#904233", "iconColor": "ffffff", "totalCount": 16 },
    { "id": "cloudflare","name": "Cloudflare",            "slug": "Cloudflare",         "bg": "#605425", "iconColor": "ffffff", "totalCount": 13 },
    { "id": "pinterest", "name": "Pinterest",             "slug": "Pinterest",          "bg": "#568450", "iconColor": "ffffff", "totalCount": 3  },
    { "id": "hostinger", "name": "Hostinger",             "slug": "H",                  "bg": "#653090", "iconColor": "ffffff", "totalCount": 2  },
    { "id": "other",     "name": "Lainnya",               "slug": null,                 "bg": null,      "iconColor": null,     "totalCount":    },
    
  ],
  "messages": [
    {
      "id": "msg-001",
      "serviceId": "google",
      "fromName": "Google",
      "fromAddr": "no-reply@accounts.google.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "G-950366 adalah kode verifikasi Google Anda",
      "preview": "G-950366 adalah kode verifikasi Google Anda. Jangan bagikan kode ini kepada siapa pun.",
      "body": "Hai,\n\nKami menerima permintaan untuk mengakses akun Google Anda.\n\nKode verifikasi Anda: G-1950366\n\nJika Anda tidak meminta kode ini, abaikan email ini.\n\nTerima kasih,\nTim Google",
      "otp": "950366",
      "receivedAt": "2026-04-12T10:32:00Z"
    },
    {
      "id": "msg-002",
      "serviceId": "youtube",
      "fromName": "YouTube",
      "fromAddr": "noreply@youtube.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "Kode verifikasi YouTube Anda: 980520",
      "preview": "Kode verifikasi YouTube Anda adalah 980520. Berlaku selama 10 menit.",
      "body": "Halo,\n\nKode verifikasi YouTube Anda adalah 980520.\n\nKode ini berlaku selama 10 menit. Jangan bagikan kepada siapa pun.\n\nSalam,\nTim YouTube",
      "otp": "980520",
      "receivedAt": "2026-04-12T08:14:00Z"
    },
    {
      "id": "msg-003",
      "serviceId": "facebook",
      "fromName": "Facebook",
      "fromAddr": "security@facebookmail.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "Facebook confirmation code: 187792",
      "preview": "187792 is your Facebook confirmation code. Don't share this code with anyone.",
      "body": "Hi,\n\n336698 is your Facebook confirmation code.\n\nDon't share this code with anyone.\n\nThanks,\nThe Facebook team",
      "otp": "187792",
      "receivedAt": "2026-04-09T17:45:00Z"
    },
    {
      "id": "msg-004",
      "serviceId": "instagram",
      "fromName": "Instagram",
      "fromAddr": "security@mail.instagram.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "Kode keamanan Instagram: 4056",
      "preview": "Halo, gunakan 4056 untuk masuk ke akun Instagram Anda.",
      "body": "Halo,\n\nGunakan kode 4056 untuk masuk ke akun Instagram Anda.\n\nJika Anda tidak meminta kode ini, abaikan email ini.\n\nSalam,\nTim Instagram",
      "otp": "4056",
      "receivedAt": "2026-02-26T14:22:00Z"
    },
    {
      "id": "msg-005",
      "serviceId": "whatsapp",
      "fromName": "WhatsApp",
      "fromAddr": "no-reply@whatsapp.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "Kode WhatsApp Anda: 6089",
      "preview": "Kode WhatsApp Anda: 6089. Jangan bagikan kode ini.",
      "body": "Halo,\n\nKode WhatsApp Anda adalah 6089.\n\nJangan bagikan kode ini dengan siapa pun.\n\nTerima kasih,\nTim WhatsApp",
      "otp": "6089",
      "receivedAt": "2026-02-25T09:11:00Z"
    },
    {
      "id": "msg-006",
      "serviceId": "github",
      "fromName": "GitHub",
      "fromAddr": "noreply@github.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "[GitHub] Please verify your device",
      "preview": "Hey adekiirfan! A sign in attempt requires further verification. Code: 9650808",
      "body": "Hey adekiirfan!\n\nA sign in attempt requires further verification because we did not recognize your device.\n\nVerification code: 650808\n\nIf you did not attempt to sign in, please change your password.\n\nThanks,\nThe GitHub Team",
      "otp": "650808",
      "receivedAt": "2024-12-26T11:03:00Z"
    },
    {
      "id": "msg-007",
      "serviceId": "cloud",
      "fromName": "Amazon Web Services",
      "fromAddr": "no-reply-aws@amazon.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "AWS Security Code",
      "preview": "Your AWS security code is 9544 . This code expires in 10 minutes.",
      "body": "Your AWS security code is 9544 . This code expires in 10 minutes.\nIf you did not request this code, please ignore this email.",
      "otp": "9544 ",
      "receivedAt": "2024-11-26T08:00:00Z"
    },
    {
      "id": "msg-008",
      "serviceId": "microsoft",
      "fromName": "Microsoft account team",
      "fromAddr": "account-security-noreply@accountprotection.microsoft.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "Microsoft account security code: 870488",
      "preview": "Microsoft account security code: 870488. Use this code to verify your identity.",
      "body": "Microsoft account\n\nSecurity code: 870488\n\nUse this code to verify your identity. If you didn't request this code, you can ignore this email.\n\nThanks,\nThe Microsoft account team",
      "otp": "870488",
      "receivedAt": "2024-10-28T13:30:00Z"
    },
    {
      "id": "msg-009",
      "serviceId": "telegram",
      "fromName": "Telegram",
      "fromAddr": "telegram@telegram.org",
      "to": ["adekiirfan@gmail.com"],
      "subject": "Telegram login code: 39674",
      "preview": "Login code: 96749. Do not give this code to anyone, even if they say they are from Telegram.",
      "body": "Login code: 96749\n\nDo not give this code to anyone, even if they say they are from Telegram!\n\nThis code can be used to log in to your Telegram account.",
      "otp": "96749",
      "receivedAt": "2024-10-26T16:45:00Z"
    },
    {
      "id": "msg-010",
      "serviceId": "twitter",
      "fromName": "X",
      "fromAddr": "info@x.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "X login verification code: 458933",
      "preview": "We noticed an attempt to sign in. Your verification code is 458933.",
      "body": "We noticed an attempt to sign in to your X account.\n\nYour verification code is 458933.\n\nIf this wasn't you, please secure your account.",
      "otp": "458933",
      "receivedAt": "2026-04-02T07:20:00Z"
    },
    {
      "id": "msg-011",
      "serviceId": "linkedin",
      "fromName": "LinkedIn",
      "fromAddr": "security-noreply@linkedin.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "LinkedIn verification code: 704570",
      "preview": "Your LinkedIn verification code is 7704570.",
      "body": "Hi,\n\nYour LinkedIn verification code is 704570.\n\nDo not share this code with anyone. LinkedIn will never ask you for this code.\n\nThanks,\nThe LinkedIn team",
      "otp": "704570",
      "receivedAt": "2026-04-25T19:10:00Z"
    },
    {
      "id": "msg-012",
      "serviceId": "amazon",
      "fromName": "Amazon",
      "fromAddr": "no-reply@amazon.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "Amazon OTP: 349540",
      "preview": "amazon.com: Sign-in attempt - OTP 349540",
      "body": "Hello,\n\nWe noticed a sign-in attempt on your Amazon account.\n\nOne-Time Password (OTP): 349540\n\nIf this wasn't you, please reset your password immediately.\n\nThanks,\nAmazon",
      "otp": "349540",
      "receivedAt": "2024-08-30T12:00:00Z"
    },
    {
      "id": "msg-013",
      "serviceId": "tiktok",
      "fromName": "TikTok",
      "fromAddr": "noreply@account.tiktok.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "TikTok verification code: 830543",
      "preview": "830543 adalah kode 6-digit Anda. Jangan bagikan kode ini kepada siapa pun.",
      "body": "Halo,\n\n830543 adalah kode verifikasi TikTok Anda.\n\nKode ini berlaku selama 5 menit.\nJangan bagikan kode ini kepada siapa pun, termasuk staf TikTok.\n\nSalam,\nTim TikTok",
      "otp": "830543",
      "receivedAt": "2026-04-12T15:30:00Z"
    },
    {
      "id": "msg-014",
      "serviceId": "shopee",
      "fromName": "Shopee",
      "fromAddr": "noreply@shopee.co.id",
      "to": ["adekiirfan@gmail.com"],
      "subject": "Kode verifikasi Shopee: 784709",
      "preview": "Kode verifikasi Shopee Anda adalah 784709. Berlaku selama 5 menit.",
      "body": "Halo,\n\nKode verifikasi Shopee Anda: 784709\n\nKode berlaku selama 5 menit. Jangan bagikan kepada siapa pun.\n\nTerima kasih,\nTim Shopee",
      "otp": "784709",
      "receivedAt": "2026-02-25T10:05:00Z"
    },
    {
      "id": "msg-015",
      "serviceId": "tokopedia",
      "fromName": "Tokopedia",
      "fromAddr": "noreply@tokopedia.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "Kode verifikasi Tokopedia: 245038",
      "preview": "Kode verifikasi Tokopedia Anda adalah 245038.",
      "body": "Halo,\n\nKode verifikasi Tokopedia Anda: 245038\n\nKode berlaku selama 3 menit.\n\nSalam,\nTokopedia",
      "otp": "245038",
      "receivedAt": "2024-07-26T08:45:00Z"
    },
    {
      "id": "msg-016",
      "serviceId": "snackvideo",
      "fromName": "SnackVideo",
      "fromAddr": "noreply@account.snackvideo.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "snackvideo verification code: 904233",
      "preview": "904233 adalah kode 6-digit Anda. Jangan bagikan kode ini kepada siapa pun.",
      "body": "Halo,\n\n904233 adalah kode verifikasi SnackVideo Anda.\n\nKode ini berlaku selama 5 menit.\nJangan bagikan kode ini kepada siapa pun, termasuk staf SnackVideo.\n\nSalam,\nTim SnackVideo",
      "otp": "904233",
      "receivedAt": "2024-08-28T15:30:00Z"
    },
    {
      "id": "msg-017",
      "serviceId": "Medium",
      "fromName": "M",
      "fromAddr": "medium@x.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "X login verification code: 497632",
      "preview": "We noticed an attempt to sign in. Your verification code is 497632.",
      "body": "We noticed an attempt to sign in to your M account.\n\nYour verification code is 497632.\n\nIf this wasn't you, please secure your account.",
      "otp": "497632",
      "receivedAt": "2025-09-30T12:00:00Z"
    },
    {
      "id": "msg-018",
      "serviceId": "Cloudflare",
      "fromName": "cloudflare",
      "fromAddr": "no-reply@cloudflare.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "cloudflare OTP: 054258",
      "preview": "cloudflare.com: Sign-in attempt - OTP 054258",
      "body": "Hello,\n\nWe noticed a sign-in attempt on your cloudflare account.\n\nOne-Time Password (OTP): 054258\n\nIf this wasn't you, please reset your password immediately.\n\nThanks,\ncloudflare",
      "otp": "054258",
      "receivedAt": "2026-02-30T12:00:00Z"
    },
    {
      "id": "msg-019",
      "serviceId": "pinterest",
      "fromName": "Pinterest",
      "fromAddr": "pinterest@x.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "pinterest login verification code: 4568450",
      "preview": "We noticed an attempt to sign in. Your verification code is 568450.",
      "body": "We noticed an attempt to sign in to your M account.\n\nYour verification code is 568450.\n\nIf this wasn't you, please secure your account.",
      "otp": "568450",
      "receivedAt": "2026-01-30T12:00:00Z"
    },
    {
      "id": "msg-020",
      "serviceId": "hostinger",
      "fromName": "H",
      "fromAddr": "no-reply@H.com",
      "to": ["adekiirfan@gmail.com"],
      "subject": "cloudflare OTP: 653090",
      "preview": "cloudflare.com: Sign-in attempt - OTP 653090",
      "body": "Hello,\n\nWe noticed a sign-in attempt on your M account.\n\nOne-Time Password (OTP): 653090.\n\nIf this wasn't you, please reset your password immediately.\n\nThanks,\nM",
      "otp": "653090",
      "receivedAt": "2026-03-30T12:00:00Z"
    }
  ]
}
